### ISSUE TITLE
Associate multiple keys to an operation

### ISSUE THREAD

**Issue by zbx1425** [magicant/bve-autopilot#56]
Many trains has multiple buttons for starting ATO, which must be pushed simultaneously.

I wonder if it is possible to simulate such behavior.

**Comment by magicant** [comment]
Thanks for the suggestion! I absolutely want this feature, too!

Now I think the format of the config file could be extended so that two or more keys can be specified for a single function:

```ini
[key]
atostart = 14&15
```

I'll implement this in a future version.
