### ISSUE TITLE
Alternative ATO behavior

### ISSUE THREAD

**Issue by zbx1425** [magicant/bve-autopilot#57]
Some ATO implementions, such as Trainguard MT by Siemens, has a behavior that is only a little bit different from that of bve-autopilot.
That is, the ATO turns off once the mascon leaves the neutral position, and will not resume operation automatically until the driver pushes the ATO start button again.
Is it possible to implement this, as a selectable behavior from the configuration file?

**Comment by magicant** [comment]
This behavior is interesting. I think I can implement this in a future version.

**Comment by zbx1425** [comment]
Thank you so much!
Actually I feel this behavior is a bit like that on the airplane, which also disconnects when intervened and stays off until manually connected again.

As of more detail, the ATO start butons on trains equipped with TGMT features a green backlight, which indicates the status of the system:
- Illuminated: ATO is controlling the train.
- Flashing: ATO can be connected right now (Doors closed, reverser forward, mascon at neutral, AM mode is preselected, etc.)
- Dark: ATO is now disabled (the conditions are not satisfied)

By the way, I am actually able to implement these features by myself.
That is, I created a standalone plugin which simulates the behavior of TGMT. When this plugin is in ATO mode, it uses P/Invoke to call bve-autopilot, which is set to "depart" automatically once the doors are closed.
I just keep bve-autopilot running and doing all the calculations in background, and I use my plugin as a medium to apply the results only when the plugin is in ATO mode. And it works fine so far!

**Comment by magicant** [comment]
> That is, I created a standalone plugin which simulates the behavior of TGMT. When this plugin is in ATO mode, it uses P/Invoke to call bve-autopilot, which is set to "depart" automatically once the doors are closed.
> I just keep bve-autopilot running and doing all the calculations in background, and I use my plugin as a medium to apply the results only when the plugin is in ATO mode. And it works fine so far!

Wow! That's an amazing technique!!!

**Comment by magicant** [comment]
The implementation has been pushed to the master branch and will be included in the next release.

I don't intend to perfectly imitate the behavior of TGMT (I don't know its behavior very well after all) but I think the new behavior will be helpful to simulate something similar to it.

(Do you need instructions in English to configure the new behavior? Note that the default behavior has not been changed in any way, so you need to modify the config file for the new behavior.)

**Comment by zbx1425** [comment]
Thank you so much for your courtesy!
My development on TGMT is also abandoned, because I also don't know its behavior very well...
The driver's cab does not have any window here, so the only way I can know how it behaves is to seek help from an actual driver. There are documents leaked online, but these are not of great detail.
Some P/Invoke would be still required, as TGMT has all the complex things like mode switching etc. In that way I am afraid I won't be able to make use of the new features.
Thank you so much!
Your Japanese instructions on wiki is readable with the help of machine translation, so I think there is no need for English instruction.
