### ISSUE TITLE
TASC制御状態の表示を点灯・消灯するタイミングを設定できるか？

### ISSUE THREAD

**Issue by Gorome** [magicant/bve-autopilot#73]
このプラグインが主に用いられる路線データといえば、東急東横線や目黒線・東京メトロ副都心線や南北線といったところであろう。特に前者に関しては動画サイト上で運転台計器類の動作も映った前面展望動画も多数ある。

　しかしながら、それらの動画を見る限り、運転台上の「TASC制御」灯は定位置に停車し開扉したタイミング(主に東急線内)、もしくは転動防止動作を手動で行うなどした一定のタイミング(主にメトロ線内)で消灯している。
　それに対し、現在の本プラグインの仕様上、上述の「TASC制御」灯に対応するbve運転台パネル出力の「tascmonitor」は閉扉しない限り点灯し続ける。
　また、絶対式停止位置設定地上子をmapファイルの0ｍ地点などに一括で設定した場合、走行中・停車中は常時「tascmonitor」が点灯し続ける。

　というわけで、TASC制御状態の表示を点灯・消灯するタイミングを設定できないだろうか？
例えば、
- 停止位置手前400mなどの指定した位置で点灯する
- 開扉した場合などには消灯する

などである。

**Comment by magicant** [comment]
> 停止位置手前400mなどの指定した位置で点灯する

tascmonitor の点灯タイミングは停止位置設定地上子を置く場所によって変えられるから、別な方法で設定できるようにするインセンティブはあまりないかなぁ……。
どのみち停車駅の数だけ停止位置を調べて地上子を置かないといけないので、ついでに地上子の置き場所を調整するくらいは手間というほどではないかと。

> 開扉した場合などには消灯する

tascmonitor の消灯タイミングは確かにカスタマイズ性を上げてもいいかもしれない。
(開扉時に tascmonitor が消灯するように見せかけるだけなら tascmonitor ランプの上に door ランプを重ねれば現行版でもできそうな気はするが、ちょっとトリッキーかな)

開扉時に消す、閉扉時に消す、開扉後一定時間たったら消す、開扉後一定以上の手動ブレーキを掛けたら消す……あと何かあるかな。

ところでこれ、停止後に TASC がいつまでブレーキをかけ続けるのかと連動すべき気がしてきた。

**Comment by Gorome** [comment]
> 開扉した場合などには消灯する　の補足

　ばーたー氏謹製の営団01系をTASC改造した際、ご指摘の通りbveデフォルトのdoorrXやdoorlXで表示灯を擬似的に消灯させるように見せかけたが、各号車のドアが閉まるのにはバラつきもあり、それらが消灯するタイミングと戸閉灯（door）が点灯するタイミングにコンマ秒ほどのラグがどうしても出てしまう。
　ちなみに、このデータのデフォルトプラグインである高橋氏謹製のメトロ総合プラグインには、ats82【知らせ灯（滅灯）】が搭載されているが、現在出回っているデータにそれを用いたものはなく、おまけにそちらを使ったとしても意図する動作をしない。
（Datailmanagerとの相性問題なのか、そもそもダミーかはさておき…）

＞ところでこれ、停止後に TASC がいつまでブレーキをかけ続けるのかと連動すべき気がしてきた。
　メトロ線内の場合、TASCで停止した際には転動防止のためB4まで制動することになっているようで、それを踏まえてUnicorn氏謹製のATO/TASCプラグインは停車4秒後にTASCブレーキは解除され、転動防止を怠るとブレーキが緩解されてしまう。実車がそのような動作なのかは保安上確認することができないが…。。。

**Comment by magicant** [comment]
JR 横浜線だと停止 1 秒後くらいで "TASC パターン" ランプが消えるのか…… ([参考動画](https://youtu.be/-D-usNckgsE?t=50))
やっぱり制御ランプ消灯タイミングは TASC ブレーキ緩解タイミングとは別で設定できるようにしないとダメか?

都営新宿線は停止 1 秒前くらいにランプが消えているように見えるがこれが何を意味しているのかはよく分からない。([参考動画](https://youtu.be/9Mzql-eypr8?t=41))

**Comment by magicant** [comment]
TASC 制御ランプ消灯と TASC ブレーキ緩解のタイミングを設定ファイルでそれぞれ以下から選べるようにする方針で検討中:

* 停止してからの秒数
* ドアが開いてからの秒数
* 停止後 TASC ブレーキ以上の強さで手動ブレーキをかけたときからの秒数
* 特に設定しない

ただし、上記どの設定でもドアが閉まったらその瞬間に TASC の状態はリセットされる。
