### ISSUE TITLE
ハンドル位置を取得したい

### ISSUE THREAD

**Issue by ktr8703** [magicant/bve-autopilot#95]
はじめまして。ATSプラグインの制作をしている者です。素晴らしいプラグインを公開していただき、ありがとうございます。

私のプラグインの使用を想定しているのが、TASCが動作中の場合にもブレーキハンドル・力行ハンドルの位置を運転台に表示する車両なのですが、現状ですと、ブレーキハンドル・力行ハンドルの位置をbve-autopilotから取得する方法がないように思います。

差し支えなければbve-autopilotから取得したく考えておりますので、運転台パネルでこれらを出力できるようにしていただけますと幸甚に存じます。ATO・TASC使用中でもハンドル位置を表示する車両は少なくありませんので、これらを取得可能にすることは、他のユーザの利便性の向上にも資すると考えております。

お手数をおかけいたしますが、ご検討のほどよろしくお願いいたします。

**Comment by magicant** [comment]
拙作のプラグインを楽しんでくださっているようでありがとうございます。

やりたいこと次第では既存の機能で達成可能かと思います。

- 手動のハンドル操作と ATO/TASC による自動操作を合わせた、実際に効いている力行・ブレーキの強さをパネルに出したい場合
    -  [ここ](https://github.com/magicant/bve-autopilot/wiki/%E9%81%8B%E8%BB%A2%E5%8F%B0%E3%83%91%E3%83%8D%E3%83%AB%E5%87%BA%E5%8A%9B%E4%BB%95%E6%A7%98#%E3%83%9E%E3%82%B9%E3%82%B3%E3%83%B3%E3%83%96%E3%83%AC%E3%83%BC%E3%82%AD%E6%8C%87%E4%BB%A4)に説明があるように autopilot.ini で `power`, `brake` を設定し、パネル設定ファイルで対応するインデックスを設定 (`subjectKey = atsXX`) すれば出力されます。
- ATO/TASC による自動操作に関係なく、手動のハンドル操作の状態のみをパネルに出したい場合
    - BVE 本体に元から備わっている[パネル設定](http://bvets.net/jp/edit/formats/vehicle/panel.html#subject)で可能です。パネル設定ファイルで直接 `subjectKey = power`, `subjectKey = brake` を設定すれば出力されます。
- ↑この手動のハンドル操作の状態を直接パネルに出すのではなくて、bve-autopilot と同時利用している別のプラグインに情報を送りたい場合
    - これがやりたい場合は、確かに現状では不可能と思いますので、実装を検討いたします。(が、これはやや特殊なユースケースかと思います。プラグインを動作させる順番を変えることで回避できる可能性もあります。)
- 手動のハンドル操作に関係なく、ATO/TASC による自動操作の力行・ブレーキの状態のみをパネルに出したい場合
    - これも現状では不可能ですので、これがやりたい場合は検討いたします。(が、文面を読む限りやりたいことはこれではありませんね?)
- その他、上記以外にやりたいことがある場合、恐れ入りますがもう少し内容を説明いただければと思います。

**Comment by ktr8703** [comment]
早速ご返信くださり、ありがとうございます。

私がしようとしていることは、

- ↑この手動のハンドル操作の状態を直接パネルに出すのではなくて、bve-autopilot と同時利用している別のプラグインに情報を送りたい場合

に該当します。
TASCによる転動防止ブレーキを自前で実装しようと考えているほか、TASCのMonitor表示灯（TASCパターン表示灯）に介入して一定の条件で消灯させようと考えており、bve-autopilot の後に私が制作しているプラグインを読み込む必要がある一方で、計器画面に表示するブレーキ・力行ノッチ表示は計器画面のカクつきを再現するためpanel出力をしようと考えており、私のプラグインでマスコン位置を取得する必要もあるのです。

bve-autopilot を2つのプラグインで挟めば解決することができますが、可能ならば1つのプラグインにしたい思いがあり、この度のお願いをいたしました。ご検討くださいますと、大変ありがたく存じます。

この度は丁重にご対応くださりありがとうございます。
よろしくお願いいたします。

**Comment by magicant** [comment]
説明ありがとうございます。理解しました。

**Comment by magicant** [comment]
[運転台パネル出力仕様](https://github.com/magicant/bve-autopilot/wiki/%E9%81%8B%E8%BB%A2%E5%8F%B0%E3%83%91%E3%83%8D%E3%83%AB%E5%87%BA%E5%8A%9B%E4%BB%95%E6%A7%98)に `powerin` と `brakein` の説明を追加しました。この仕様で実装予定です。

**Comment by ktr8703** [comment]
お知らせいただきありがとうございます。かしこまりました。
非常に早くご対応いただき、大変ありがたく存じます。
よろしくお願いいたします。

**Comment by magicant** [comment]
[v1.15](https://github.com/magicant/bve-autopilot/releases/tag/v1.15) で対応しました。お試しください。

**Comment by ktr8703** [comment]
お知らせいただきありがとうございます。
ダウンロードして確認いたしました。
Panelにより、後に読み込んだプラグインでハンドル位置を取得することができました。
思っていたとおりの機能です。

この度は親切にご対応いただき、ありがとうございました。
今後ともよろしくお願いいたします。
