### ISSUE TITLE
ATOはsnp形式のデータでは正常に動作しません

### ISSUE THREAD

**Issue by winup-zhou** [magicant/bve-autopilot#98]
1.信号パターンはATS-P即時停止地上子（4#、5#）で更新できません。
2.ATS-P分岐パターン（6、16#）、下り勾配パターン（8、18#）、誘導パターン（11、21#）、臨時パターン（10、20#）地上子は読み取れません。

**Comment by magicant** [comment]
snp の地上子は ATO を動作させるのに十分な情報を提供しないため、使用できません。自分で 1012 番や 1006 番の地上子を追加して使用してください。

**Comment by winup-zhou** [comment]
thank you
